name: CMake-action

# trigger
on:
  push:
    branches: [ "dev" ]


env:
  BUILD_TYPE: Debug
  TEST: on

jobs:
  # job name "build"
  build:
    
    #version of ubuntu linux runner
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTEST=${{env.TEST}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./test 

